### ISSUE TITLE
Important Sections of Terms of Service?

### ISSUE THREAD

**Issue by davidklebanoff** [Automattic/legalmattic#20]
In the HTML version of the [Wordpress Terms of Service](https://en.wordpress.com/tos/), several sections, such as 13 - 16, appear more "important" and are displayed within a yellow container to make them stand out.

Is there a legal significance to this? I am not a lawyer... I believe there may be in the same way that many Terms of Service agreements have all-caps warranty sections. Thus, it would seem the markdown copies in this repository are "missing information" and should probably reflect whatever meaning is being conveyed through the HTML version.

Thoughts?

**Comment by clickysteve** [comment]
Hey @davidklebanoff - thanks for spotting and flagging this! 

The yellow container is definitely on purpose, and the equivalent emphasis has not been carried over to the Markdown version. I've bolded those sections on the GitHub repo as a result to give some sort of correlation.
