### ISSUE TITLE
Terms of Service - use of undefined "our services"

### ISSUE THREAD

**Issue by davidklebanoff** [Automattic/legalmattic#21]
In several places in the Terms of Service, the words "our services" are used in which _services_ is not capitalized. For example, in the first terms of service paragraph we see:

> By accessing or using any part of **our services**, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access or use any of **our services**.

I believe the word _services_ in "our services" should be capitalized in this context, as it is a defined term.

There are other sections in which I noticed this issue as well, so it's worth evaluating the whole document.

Again, the usual disclaimer: I am not a lawyer.

**Comment by clickysteve** [comment]
Reviewed and fixed this in https://github.com/Automattic/legalmattic/commit/56aa621a1bb9788b93e6e0cc519b2546aa72cd8f - ignore the above commit.
