### ISSUE TITLE
Terms of Service - use of undefined "agreement"

### ISSUE THREAD

**Issue by davidklebanoff** [Automattic/legalmattic#22]
In several places in the Terms of Service, the words "this agreement" are used in which agreement is not capitalized. For example, in the first terms of service paragraph we see:

> By accessing or using any part of our services, you agree to become bound by the terms and conditions of **this agreement**. If you do not agree to all the terms and conditions of **this agreement**, then you may not access or use any of our services.

I believe the word agreement in "this agreement" should be capitalized in this context, as it is a defined term.

There are other sections in which I noticed this issue as well (such as the Limitation of Liability section), so it's worth evaluating the whole document.

Again, the usual disclaimer: I am not a lawyer.

**Comment by clickysteve** [comment]
Thanks again for your review. There is a mix of normative and defined terms when it comes to 'Agreement' in the ToS, but I spotted a few instances where this appeared to be incorrect, and have fixed it.
