### ISSUE TITLE
Terms of Service - use of undefined "Terms" and "these Terms"

### ISSUE THREAD

**Issue by davidklebanoff** [Automattic/legalmattic#23]
In the **Changes** section, the terms of service make reference to "the Terms" in the last sentence.

> However, any dispute that arose before the changes shall be governed by the **Terms** (including the binding individual arbitration clause) that were in place when the dispute arose.

_Terms_ is never defined and thus I don't think it should be capitalized. It should probably be "Terms of Service".

Additionally, in some other places "Terms" is used, but again it is not defined. For example in the VaultPress section:

> VaultPress Content. VaultPress will backup your WordPress content (e.g., your WordPress database, plugins, themes, and uploads, as well as some additional files, as described here) ("VaultPress Content"). You can view the Content that VaultPress backs up via your dashboard. You're fully responsible for your VaultPress Content. It's your responsibility to ensure that your website's Content abides by applicable laws and by **these Terms**. We don't actively review the VaultPress Content.

"these Terms" is used with a capital T here, but in many other places in the Terms of Service, lowercase "these terms" is used. This inconsistency is seen in several places in the document so I'm not sure if the solution is to define _Terms_ and change all of them to uppercase "these Terms" or simply make them all lowercase "these terms".

Again, the usual disclaimer: I am not a lawyer.

**Comment by clickysteve** [comment]
Hey David, thanks for this one as well. There is a mix of the normative use of 'terms' and 'Terms' in the ToS, but I've gone ahead and made updates to make sure the defined term is set out properly. Closing this out as a result!
