### ISSUE TITLE
Add more pseudonyms for Automattic Inc. in Terms of Service

### ISSUE THREAD

**Issue by davidklebanoff** [Automattic/legalmattic#24]
Currently the pseudonyms for Automattic Inc. in the Terms of Service include "Automattic" and "we".

> If you reside in the United States or Brazil, your agreement is with Automattic Inc. (US), and if you reside outside of the United States or Brazil, your agreement is with Aut O'Mattic Ltd. (Ireland) (each, **"Automattic"** or **"we"**).

I think inclusion of "our" and "us" would be more thorough, especially since those terms are used throughout.

> If you reside in the United States or Brazil, your agreement is with Automattic Inc. (US), and if you reside outside of the United States or Brazil, your agreement is with Aut O'Mattic Ltd. (Ireland) (each, **"Automattic", "we", "our",** or **"us"**).

**Comment by pawinee2135** [comment]
Support Us in terms of service for play Game Bingo Bitz.
Plass

**Comment by canhductu1980** [comment]
tran thanh cam on

**Comment by Wxjdjfrsgagjxyf** [comment]
بدنا بف

**Comment by Wxjdjfrsgagjxyf** [comment]
لوسمحت بدي احمل نغمات نظام ابيايد

**Comment by tungto99** [comment]
Happy happy 🤦

**Comment by clickysteve** [comment]
I am going to close out this request as it is a number of years old and the language of the ToS has changed since then. The feedback has been noted and taken into consideration, but won't be directly implemented at the moment.
