### ISSUE TITLE
Incorrect hyperlink

### ISSUE THREAD

**Issue by N8Solutions** [Automattic/legalmattic#31]
Hello,

The commit for the updated terms of services located [here](https://github.com/Automattic/legalmattic/commit/98cdfb8b6077f578c5e0d1fc6004753ca1b36248#diff-8c763ba3f2c4343589f0ed049fe0b69d) references a blog article at the very top however the hyperlink for it is incorrect. The date is off by 1 day. It has the 13th when it should be the 14th..
This is the link the commit has:
http://en.blog.wordpress.com/2018/05/13/new-privacy-features-and-updated-policies

When it should be:
http://en.blog.wordpress.com/2018/05/14/new-privacy-features-and-updated-policies

![image](https://user-images.githubusercontent.com/12389693/40321433-b54d4110-5d37-11e8-9629-dbab3ffde7a1.png)

kind regards

**Comment by clickysteve** [comment]
Thank you for noting this. Rather than going back to edit this, I will leave this as a note and close the Issue out in the meantime.
