### ISSUE TITLE
Other languages (e.g. Spanish) available?

### ISSUE THREAD

**Issue by cliffordp** [Automattic/legalmattic#6]
I see the TOS available in Spanish at http://es.wordpress.com/tos/ but I don't see the Spanish language version available here on Github.

Please explain how the Spanish version is served up (text available somewhere to be added here or some automatic translator that generates it)?

**Comment by theyuv** [comment]
Hello and thank you for the translations (of the ToS).
Is there a reason why the Privacy Policy isn't translated into other languages as well? Is it not necessary in other languages?
Thanks.

**Comment by clickysteve** [comment]
Hey there,

No specific reason. We strive to have as many of our documents as possible translated - and will look into seeing whether it’s possible/practical for the privacy policy. It might need to wait until the next round of changes, but will put it on the list!
