### ISSUE TITLE
Add linkable section IDs for easy linking to specific sections of the TOS and privacy policy

### ISSUE THREAD

**Issue by pierorocca** [Automattic/legalmattic#71]
It would greatly improve usability if the TOS and Privacy Policy included section IDs that are linkable. Given the TOS covers many products, and both consumer and merchant audiences, linking to specific sections is convenient and enables targeted callouts.

**Comment by pierorocca** [comment]
Section 5 is the only section with an ID currently fyi.

![image](https://github.com/Automattic/legalmattic/assets/109928953/892cdf02-6737-4e5b-8743-40898c58b27a)

**Comment by pierorocca** [comment]
Perhaps when the markdown is posted to Wordpress.com site, the markdown processor is not generating linkable headings. If that's the case could we add in custom heading ID? https://www.markdownguide.org/extended-syntax/#heading-ids

**Comment by Stariga** [comment]
https:// www.pornokidsvideo.org/except-githab

**Comment by pierorocca** [comment]
Closing as complete as I updated the TOS document many months ago to include the requested section IDs.
